### ISSUE TITLE
Specify domain as a switch?

### ISSUE THREAD

**Issue by mjsweet** [pothi/backup-wordpress#15]
Hi Dude!

Is it possible to specify the domain as a switch e.g:

$ ./full-backup.sh --domain example2.com
$ ./full-backup.sh --domain example3.com

Etc.

If you can help it would be appreciated! Love the script BTW :D 

Matt

**Comment by pothi** [comment]
Thanks for checking out the backup scripts, Matt!

Of course, it is possible to add `--domain` switch in the script. I had a plan to use shorter form (`-d`), though (when I merge all three scripts)

Currently, if you are not aware, it is possible to specify the domain without a switch like this...

./full-backup.sh example1.com
./full-backup.sh example2.com
./full-backup.sh example3.com

I will try to implement it as and when I get time. I already have a long list of things to do as mentioned in the roadmap.

**Comment by mjsweet** [comment]
Ah!! If you could add that to the readme I'm sure others would appreciate it!

Thank you so much!

**Comment by pothi** [comment]
Thanks for the feedback.

Sure. That was indeed my lack of understanding on others perceive things. Looking at the docs now, it is definitely lacking the basics on how the scripts work. I will update it as soon as possible.

Thanks again,
Pothi
