### ISSUE TITLE
readme: twitter username has a ']'

### ISSUE THREAD

**Issue by Stankye** [pothi/backup-wordpress#21]
`Please ping me on [Twitter](https://twitter.com/pothi]) or [send me a message](https://www.tinywp.in/contact/).`

to

`Please ping me on [Twitter](https://twitter.com/pothi) or [send me a message](https://www.tinywp.in/contact/).`

Amazing work on the scripts!

idea: add rclone support, would open up a ton of options for backup locations.

**Comment by pothi** [comment]
Hi @Stankye ,

Thank you for your time testing the repo and creating this issue. It's fixed now.

[rclone](https://rclone.org/) looks nice. I will explore it further.

Thanks again,
Pothi.
