### ISSUE TITLE
Report backup size in output

### ISSUE THREAD

**Issue by StomproLARL2023** [pothi/backup-wordpress#26]
Hello, I would find it useful for the command to output stats on the backup size.  

After the "Latest backup is at" line
Backup size [bytes]: X
Backup size [Human]: Y

Where Human = du -h mode.

And if you wanted to be really fancy include the unencrypted size and the compression ratio.

This would just make it easier to have an awareness of the backup size.

I think this should go out in the success email also.

Thanks

**Comment by pothi** [comment]
Good idea!
